name: ${name}
version: ${version}
main: org.equinoxprojects.luxurystaff.LuxuryStaff
author: Evisual
api-version: 1.16

commands:
  staffchat:
    description: Command that allows staff to toggle chat
    permission: staff.command.staffchat
    aliases: [sc]
  config:
    description: Command to reload config
    permission: staff.command.config.reload